version: '3'
services:
  payhere-app:
    build: .
    container_name: payhere-app
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - test-db
    networks:
      - payhere-network
  test-db:
    image: mysql:5.7
    container_name: mysql-container
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: Asia/Seoul
      MYSQL_DATABASE: 'homework-db'
    volumes:
      - ./test-db:/var/lib/mysql
      - ./test-db:/var/lib/mysql-files
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    platform: linux/amd64
    networks:
      - payhere-network

networks:
  payhere-network:
    driver: bridge
