spring:
  profiles:
    active: local
    include: jwt

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/homework-db?useUnicode=true&characterEncoding=utf-8

  # JPA Open-In-view
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
#    generate-ddl: true

# Log Setting
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace



